/**
 * Level Up Life — centralized API client (mocked).
 * Every method mirrors a future REST endpoint on the Python backend.
 * The frontend never trusts itself for balances, purchases, payments or
 * third-party sync: the backend must validate and persist every action.
 */
export type Category =
  | "Salud"
  | "Estudio"
  | "Trabajo"
  | "Finanzas"
  | "Relaciones"
  | "Familia"
  | "Ocio"
  | "Espiritualidad";

export const CATEGORIES: Category[] = ["Salud", "Estudio", "Trabajo", "Finanzas", "Relaciones", "Familia", "Ocio", "Espiritualidad"];

export interface LifeStat {
  category: Category;
  level: number;
  xp: number;
  nextLevelXp: number;
  reflection?: string;
}
export type Difficulty = "Fácil" | "Media" | "Difícil";
export type TaskType = "daily" | "main";

export interface Player {
  id: string;
  name: string;
  handle: string;
  level: number;
  currentXp: number;
  nextLevelXp: number;
  totalPoints: number;
  streak: number;
  multiplier: number;
}

export interface LevelRank { min: number; max: number; key: string }
export const LEVEL_RANKS: LevelRank[] = [
  { min: 1, max: 4, key: "novice" }, { min: 5, max: 9, key: "explorer" },
  { min: 10, max: 19, key: "driver" }, { min: 20, max: 34, key: "elite" },
  { min: 35, max: 49, key: "master" }, { min: 50, max: 74, key: "legend" },
  { min: 75, max: 999, key: "god" },
];
export function getLevelRank(level: number) { return LEVEL_RANKS.find((rank) => level >= rank.min && level <= rank.max) ?? LEVEL_RANKS[0]; }

export interface Mission {
  id: string;
  title: string;
  category: Category;
  difficulty: Difficulty;
  xp: number;
  type: TaskType;
  completed: boolean;
  /** ISO date (YYYY-MM-DD) when the mission was completed */
  completedOn?: string;
  /** true = title comes from the translation catalog (demo data) */
  i18n?: boolean;
  /** translation key for missions generated by the spin wheel */
  titleKey?: string;
  /** ISO date (YYYY-MM-DD) deadline shown in the agenda */
  dueDate?: string;
  /** local time (HH:mm) used by the daily agenda */
  scheduledTime?: string;
  /** coaching reminder generated for this task */
  reminder?: string;
  /** check items; the server keeps them in sync with other apps */
  checklist?: { id: string; text: string; done: boolean }[];
}

export interface Friend {
  id: string;
  name: string;
  handle: string;
  level: number;
  streak: number;
  topCategory: Category;
  balance: number;
  latestActivity?: { taskTitle: string; completedAt: string; xp: number };
}

export interface Challenge {
  id: string;
  friendId: string;
  missionTitle: string;
  stakeType: "lifecoins" | "coupon";
  stake: number | null;
  couponId?: string;
  couponRewardId?: string;
  status: "pending" | "active" | "won" | "lost";
}

export interface Reward {
  id: string;
  title: string;
  description: string;
  cost: number;
  icon: "coffee" | "game" | "movie" | "rest" | "icecream" | "dinner" | "spa" | "shopping" | "trip" | "book" | "music" | "sleep";
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  unlocked: boolean;
  progress?: number;
  icon: "flame" | "sword" | "crown" | "target" | "bolt" | "shield" | "heart" | "book" | "wallet" | "users" | "gem" | "star" | "paw" | "medal";
}

export type Slot = "character" | "outfit" | "accessory" | "scene" | "pet" | "aura";
export const SLOTS: Slot[] = ["character", "outfit", "accessory", "scene", "pet", "aura"];
const WOMEN_CHARACTERS = new Set(["char_hacker", "char_biker", "char_royal", "char_luna", "char_amara", "char_sora", "char_noor", "char_freya", "char_ruby", "char_priya"]);
export function canWearOutfit(character: string | null, outfit: string): boolean {
  if (outfit === "outfit_exec") return !WOMEN_CHARACTERS.has(character ?? "char_runner");
  if (outfit === "outfit_exec_women") return WOMEN_CHARACTERS.has(character ?? "char_runner");
  return true;
}
export type Rarity = "common" | "rare" | "epic" | "legendary";

/** All prices are in LifeCoins (in-game currency). No real money. */
export interface AvatarItem {
  id: string;
  slot: Slot;
  rarity: Rarity;
  source: "free" | "store" | "reward" | "premium";
  cost?: number;
  unlockBy?: string;
  bonus?: { category: Category; value: number };
}

export interface Theme {
  id: string;
  cost?: number;
  premium?: boolean;
  comingSoon?: boolean;
}

export interface AvatarState {
  equipped: Record<Slot, string | null>;
}

export interface Invite {
  id: string;
  from: string;
  mission: Omit<Mission, "id" | "completed">;
}

export interface SharedMission {
  id: string;
  missionId: string;
  missionTitle: string;
  recipient: string;
  status: "pending" | "accepted";
}

export interface Coupon {
  id: string;
  rewardId: string;
  sharedWith: string | null;
}

export interface Integration {
  id: string;
  name: string;
  connected: boolean;
  lastSync: string | null;
}

export interface DashboardData {
  player: Player;
  missions: Mission[];
  rewards: Reward[];
  coupons: Coupon[];
  achievements: Achievement[];
  lifeStats: LifeStat[];
  avatar: AvatarState;
  ownedItems: string[];
  ownedThemes: string[];
  themeId: string;
  invites: Invite[];
  shared: SharedMission[];
  integrations: Integration[];
  arcade: { lastSpin: string | null; lastChest: string | null };
}

export interface ChestResult { coins: number; rarity: Rarity; itemId: string | null }

export const AVATAR_ITEMS: AvatarItem[] = [
  { id: "char_runner", slot: "character", rarity: "common", source: "free" },
  { id: "char_hacker", slot: "character", rarity: "common", source: "free" },
  { id: "char_luna", slot: "character", rarity: "common", source: "free" },
  { id: "char_erik", slot: "character", rarity: "common", source: "free" },
  { id: "char_freya", slot: "character", rarity: "common", source: "free" },
  { id: "char_kai", slot: "character", rarity: "rare", source: "store", cost: 550, bonus: { category: "Estudio", value: 2 } },
  { id: "char_amara", slot: "character", rarity: "epic", source: "store", cost: 850, bonus: { category: "Trabajo", value: 3 } },
  { id: "char_mateo", slot: "character", rarity: "common", source: "free" },
  { id: "char_sora", slot: "character", rarity: "rare", source: "store", cost: 650, bonus: { category: "Salud", value: 3 } },
  { id: "char_noor", slot: "character", rarity: "epic", source: "store", cost: 950, bonus: { category: "Finanzas", value: 4 } },
  { id: "char_liam", slot: "character", rarity: "rare", source: "store", cost: 500, bonus: { category: "Familia", value: 2 } },
  { id: "char_ruby", slot: "character", rarity: "rare", source: "store", cost: 600, bonus: { category: "Salud", value: 3 } },
  { id: "char_omar", slot: "character", rarity: "epic", source: "store", cost: 900, bonus: { category: "Finanzas", value: 4 } },
  { id: "char_priya", slot: "character", rarity: "epic", source: "store", cost: 900, bonus: { category: "Espiritualidad", value: 4 } },
  { id: "char_biker", slot: "character", rarity: "rare", source: "store", cost: 600 },
  { id: "char_boss", slot: "character", rarity: "epic", source: "store", cost: 900 },
  { id: "char_athlete", slot: "character", rarity: "legendary", source: "reward", unlockBy: "badge_2" },
  { id: "char_royal", slot: "character", rarity: "legendary", source: "premium", cost: 2500 },
  { id: "outfit_street", slot: "outfit", rarity: "common", source: "free", bonus: { category: "Ocio", value: 1 } },
  { id: "outfit_focus", slot: "outfit", rarity: "rare", source: "free", bonus: { category: "Estudio", value: 3 } },
  { id: "outfit_exec", slot: "outfit", rarity: "epic", source: "store", cost: 900, bonus: { category: "Trabajo", value: 5 } },
  { id: "outfit_exec_women", slot: "outfit", rarity: "epic", source: "store", cost: 900, bonus: { category: "Trabajo", value: 5 } },
  { id: "outfit_champion", slot: "outfit", rarity: "legendary", source: "premium", cost: 1600, bonus: { category: "Salud", value: 7 } },
  { id: "acc_glasses", slot: "accessory", rarity: "common", source: "free", bonus: { category: "Estudio", value: 1 } },
  { id: "acc_headphones", slot: "accessory", rarity: "rare", source: "store", cost: 250, bonus: { category: "Ocio", value: 2 } },
  { id: "acc_cap", slot: "accessory", rarity: "rare", source: "store", cost: 300, bonus: { category: "Salud", value: 2 } },
  { id: "acc_watch", slot: "accessory", rarity: "epic", source: "store", cost: 500, bonus: { category: "Finanzas", value: 4 } },
  { id: "scene_city", slot: "scene", rarity: "common", source: "free", bonus: { category: "Trabajo", value: 1 } },
  { id: "scene_sunset", slot: "scene", rarity: "rare", source: "store", cost: 300, bonus: { category: "Relaciones", value: 3 } },
  { id: "scene_neon", slot: "scene", rarity: "rare", source: "store", cost: 450, bonus: { category: "Ocio", value: 3 } },
  { id: "scene_desert", slot: "scene", rarity: "epic", source: "reward", unlockBy: "badge_1", bonus: { category: "Espiritualidad", value: 5 } },
  { id: "scene_gold", slot: "scene", rarity: "legendary", source: "premium", cost: 1800, bonus: { category: "Finanzas", value: 8 } },
  { id: "scene_campus", slot: "scene", rarity: "rare", source: "store", cost: 500, bonus: { category: "Estudio", value: 4 } },
  { id: "scene_garden", slot: "scene", rarity: "epic", source: "store", cost: 800, bonus: { category: "Familia", value: 5 } },
  { id: "scene_rooftop", slot: "scene", rarity: "epic", source: "store", cost: 950, bonus: { category: "Trabajo", value: 6 } },
  { id: "scene_studio", slot: "scene", rarity: "rare", source: "store", cost: 700, bonus: { category: "Estudio", value: 5 } },
  { id: "scene_coast", slot: "scene", rarity: "legendary", source: "premium", cost: 1800, bonus: { category: "Espiritualidad", value: 8 } },
  { id: "pet_shepherd", slot: "pet", rarity: "rare", source: "store", cost: 600, bonus: { category: "Salud", value: 4 } },
  { id: "pet_tabby", slot: "pet", rarity: "common", source: "free" },
  { id: "pet_cat", slot: "pet", rarity: "epic", source: "store", cost: 900, bonus: { category: "Espiritualidad", value: 5 } },
  { id: "pet_robofox", slot: "pet", rarity: "legendary", source: "premium", cost: 1900, bonus: { category: "Ocio", value: 8 } },
  { id: "aura_neon", slot: "aura", rarity: "rare", source: "store", cost: 400 },
  { id: "aura_flame", slot: "aura", rarity: "epic", source: "reward", unlockBy: "badge_4" },
  { id: "aura_gold", slot: "aura", rarity: "legendary", source: "premium", cost: 2000 },
];

export const THEMES: Theme[] = [
  { id: "cyber" },
  { id: "matrix", cost: 400 },
  { id: "synthwave", cost: 700 },
  { id: "gold", cost: 1500, premium: true },
  { id: "aurora", cost: 2500, premium: true, comingSoon: true },
];

/** Spin-wheel task catalog: 2 translated tasks per life area. */
export const WHEEL_TASKS: Record<Category, string[]> = Object.fromEntries(
  CATEGORIES.map((c) => [c, [`wheel.${c}.1`, `wheel.${c}.2`]]),
) as Record<Category, string[]>;

const statSeed: Record<Category, [number, number]> = {
  Salud: [4, 120], Estudio: [5, 60], Trabajo: [6, 150], Finanzas: [3, 40],
  Relaciones: [4, 90], Familia: [5, 20], Ocio: [2, 70], Espiritualidad: [3, 10],
};

const m = (id: string, category: Category, difficulty: Difficulty, xp: number, type: TaskType, completed = false): Mission =>
  ({ id, title: id, category, difficulty, xp, type, completed, i18n: true });

const mockData: DashboardData = {
  lifeStats: CATEGORIES.map((category) => ({ category, level: statSeed[category][0], xp: statSeed[category][1], nextLevelXp: statLevelXp(statSeed[category][0]) })),
  player: { id: "usr_001", name: "Alex Rivera", handle: "@alex.levels", level: 5, currentXp: 350, nextLevelXp: 500, totalPoints: 2450, streak: 12, multiplier: 1.5 },
  missions: [
    m("daily_1", "Salud", "Media", 50, "daily"),
    m("daily_2", "Estudio", "Fácil", 30, "daily", true),
    m("daily_3", "Trabajo", "Fácil", 25, "daily"),
    m("main_1", "Trabajo", "Difícil", 120, "main"),
    m("main_2", "Estudio", "Media", 100, "main"),
    m("daily_4", "Finanzas", "Fácil", 20, "daily"),
    m("daily_5", "Relaciones", "Fácil", 30, "daily"),
    m("daily_6", "Familia", "Media", 40, "daily"),
    m("daily_7", "Espiritualidad", "Fácil", 25, "daily"),
    m("main_3", "Ocio", "Media", 60, "main"),
  ],
  rewards: [
    { id: "reward_1", title: "", description: "", cost: 300, icon: "coffee" },
    { id: "reward_2", title: "", description: "", cost: 500, icon: "game" },
    { id: "reward_3", title: "", description: "", cost: 750, icon: "movie" },
    { id: "reward_4", title: "", description: "", cost: 1200, icon: "rest" },
    { id: "reward_5", title: "", description: "", cost: 250, icon: "icecream" },
    { id: "reward_6", title: "", description: "", cost: 400, icon: "music" },
    { id: "reward_7", title: "", description: "", cost: 450, icon: "book" },
    { id: "reward_8", title: "", description: "", cost: 600, icon: "sleep" },
    { id: "reward_9", title: "", description: "", cost: 900, icon: "dinner" },
    { id: "reward_10", title: "", description: "", cost: 1100, icon: "spa" },
    { id: "reward_11", title: "", description: "", cost: 1500, icon: "shopping" },
    { id: "reward_12", title: "", description: "", cost: 3000, icon: "trip" },
  ],
  coupons: [],
  achievements: [
    { id: "badge_1", title: "", description: "", unlocked: true, icon: "sword" },
    { id: "badge_2", title: "", description: "", unlocked: true, icon: "flame" },
    { id: "badge_3", title: "", description: "", unlocked: false, progress: 68, icon: "shield" },
    { id: "badge_4", title: "", description: "", unlocked: false, progress: 40, icon: "bolt" },
    { id: "badge_5", title: "", description: "", unlocked: false, progress: 50, icon: "crown" },
    { id: "badge_6", title: "", description: "", unlocked: false, progress: 20, icon: "target" },
    { id: "badge_7", title: "", description: "", unlocked: true, icon: "heart" },
    { id: "badge_8", title: "", description: "", unlocked: false, progress: 55, icon: "book" },
    { id: "badge_9", title: "", description: "", unlocked: false, progress: 32, icon: "wallet" },
    { id: "badge_10", title: "", description: "", unlocked: false, progress: 75, icon: "users" },
    { id: "badge_11", title: "", description: "", unlocked: false, progress: 45, icon: "gem" },
    { id: "badge_12", title: "", description: "", unlocked: false, progress: 60, icon: "star" },
    { id: "badge_13", title: "", description: "", unlocked: false, progress: 25, icon: "paw" },
    { id: "badge_14", title: "", description: "", unlocked: false, progress: 12, icon: "medal" },
  ],
  avatar: { equipped: { character: "char_runner", outfit: "outfit_street", accessory: null, scene: "scene_city", pet: null, aura: null } },
  ownedItems: AVATAR_ITEMS.filter((i) => i.source === "free").map((i) => i.id),
  ownedThemes: ["cyber"],
  themeId: "cyber",
  invites: [
    { id: "inv_1", from: "@maria.fit", mission: { title: "Correr 5 km juntos", category: "Salud", difficulty: "Media", xp: 60, type: "main" } },
    { id: "inv_2", from: "@devsquad", mission: { title: "Code review semanal", category: "Trabajo", difficulty: "Fácil", xp: 35, type: "daily" } },
  ],
  shared: [],
  integrations: [
    { id: "google_fit", name: "Google Fit", connected: false, lastSync: null },
    { id: "apple_health", name: "Apple Health", connected: false, lastSync: null },
    { id: "strava", name: "Strava", connected: true, lastSync: new Date(Date.now() - 3600_000).toISOString() },
    { id: "google_calendar", name: "Google Calendar", connected: false, lastSync: null },
    { id: "notion", name: "Notion", connected: false, lastSync: null },
    { id: "discord", name: "Discord", connected: false, lastSync: null },
  ],
  arcade: { lastSpin: null, lastChest: null },
};

const wait = (ms = 650) => new Promise((resolve) => setTimeout(resolve, ms));
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

export const levelUpService = {
  // GET /api/dashboard
  async getDashboard(): Promise<DashboardData> {
    await wait(900);
    const data = clone(mockData);
    const day = (n: number) => { const d = new Date(); d.setDate(d.getDate() + n); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };
    let offset = 0;
    data.missions = data.missions.map((m) => (m.completed ? { ...m, completedOn: day(0) } : m)).map((m) => {
      if (m.type === "daily") return { ...m, dueDate: day(0) };
      offset += 2;
      return offset === 2
        ? { ...m, dueDate: day(offset), checklist: [{ id: "s1", text: "Definir objetivo", done: true }, { id: "s2", text: "Preparar materiales", done: false }, { id: "s3", text: "Revisión final", done: false }] }
        : { ...m, dueDate: day(offset) };
    });
    return data;
  },
  // POST /api/tasks/:id/complete
  async completeTask(taskId: string) { await wait(); return { taskId, success: true as const }; },
  // GET /api/friends
  async getFriends(): Promise<{ friends: Friend[]; challenges: Challenge[] }> {
    await wait(600);
    return {
      friends: [
        { id: "f1", name: "Lucía", handle: "@lucia", level: 14, streak: 9, topCategory: "Salud", balance: 7.2, latestActivity: { taskTitle: "Entrenamiento de 30 minutos", completedAt: new Date(Date.now() - 12 * 60_000).toISOString(), xp: 50 } },
        { id: "f2", name: "Diego", handle: "@diego", level: 9, streak: 4, topCategory: "Trabajo", balance: 5.8 },
        { id: "f3", name: "Valentina", handle: "@vale", level: 21, streak: 16, topCategory: "Estudio", balance: 8.1, latestActivity: { taskTitle: "Completar módulo de React", completedAt: new Date(Date.now() - 47 * 60_000).toISOString(), xp: 100 } },
      ],
      challenges: [{ id: "c1", friendId: "f1", missionTitle: "Correr 3 días esta semana", stakeType: "lifecoins", stake: 150, status: "active" }],
    };
  },
  // POST /api/friends/invite
  async inviteFriend(handle: string) { await wait(600); return { handle, success: true as const }; },
  // POST /api/challenges  (server holds the stake and decides the winner)
  async createChallenge(friendId: string, missionTitle: string, wager: { type: "lifecoins"; amount: number } | { type: "coupon"; couponId: string; rewardId: string }): Promise<Challenge> {
    await wait(600);
    return wager.type === "lifecoins"
      ? { id: `c_${Date.now()}`, friendId, missionTitle, stakeType: "lifecoins", stake: wager.amount, status: "pending" }
      : { id: `c_${Date.now()}`, friendId, missionTitle, stakeType: "coupon", stake: null, couponId: wager.couponId, couponRewardId: wager.rewardId, status: "pending" };
  },
  // POST /api/friends/:id/share-stats
  async shareStats(friendId: string) { await wait(500); return { friendId, success: true as const }; },
  // POST /api/calendar/sync  (server pushes the agenda to connected apps)
  async syncCalendar() { await wait(800); return { success: true as const }; },
  // POST /api/reminders/share  (server creates the shared reminder for the recipient)
  async shareReminder(reminderId: string, title: string, recipient: string) {
    await wait(650);
    return { reminderId, title, recipient, success: true as const };
  },
  // PUT /api/tasks/:id
  async saveTask(task: Mission): Promise<Mission> { await wait(500); return clone(task); },
  // POST /api/rewards/:id/redeem  (server issues the coupon and validates the balance)
  async redeemReward(rewardId: string): Promise<Coupon> {
    await wait(700);
    return { id: `coupon_${Date.now()}`, rewardId, sharedWith: null };
  },
  // POST /api/coupons/:id/share  (server notifies the recipient)
  async shareCoupon(couponId: string, recipient: string) { await wait(700); return { couponId, recipient, success: true as const }; },
  // POST /api/store/purchase  (points balance validated server-side)
  async buyWithPoints(productId: string) { await wait(700); return { productId, success: true as const }; },
  // PUT /api/avatar
  async saveAvatar(avatar: AvatarState) { await wait(600); return clone(avatar); },
  // PUT /api/profile/theme
  async setTheme(themeId: string) { await wait(300); return { themeId }; },
  // POST /api/achievements/rewards/:itemId/claim
  async claimReward(itemId: string) { await wait(600); return { itemId, success: true as const }; },
  // POST /api/tasks/:id/share
  async shareMission(missionId: string, missionTitle: string, recipient: string): Promise<SharedMission> {
    await wait(700);
    return { id: `share_${Date.now()}`, missionId, missionTitle, recipient, status: "pending" };
  },
  // POST /api/invites/:id/respond
  async respondInvite(inviteId: string, accept: boolean) { await wait(500); return { inviteId, accept }; },
  // POST /api/integrations/:id/connect  (OAuth handled by backend)
  async connectIntegration(id: string) { await wait(1000); return { id, connected: true, lastSync: new Date().toISOString() }; },
  // DELETE /api/integrations/:id
  async disconnectIntegration(id: string) { await wait(500); return { id, connected: false }; },
  // POST /api/integrations/:id/sync
  async syncAchievements(id: string, count: number) { await wait(1100); return { id, synced: count, at: new Date().toISOString() }; },
  // PUT /api/profile/locale
  async setLocale(locale: string) { await wait(150); return { locale }; },
  // POST /api/arcade/spin  (server picks the area + task and enforces 1 spin/day)
  async spinWheel(focus: Category | null): Promise<{ category: Category; titleKey: string; xp: number }> {
    await wait(300);
    const category = focus && Math.random() < 0.5 ? focus : CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)]!;
    const list = WHEEL_TASKS[category];
    return { category, titleKey: list[Math.floor(Math.random() * list.length)]!, xp: 40 + Math.floor(Math.random() * 3) * 20 };
  },
  // POST /api/arcade/chest  (server rolls loot and credits LifeCoins, 1 chest/day)
  async openChest(owned: string[]): Promise<ChestResult> {
    await wait(1200);
    const r = Math.random();
    const rarity: Rarity = r < 0.55 ? "common" : r < 0.85 ? "rare" : r < 0.97 ? "epic" : "legendary";
    const coins = { common: 80, rare: 180, epic: 350, legendary: 700 }[rarity];
    const pool = AVATAR_ITEMS.filter((i) => i.source === "store" && !owned.includes(i.id));
    const itemId = (rarity === "epic" || rarity === "legendary") && pool.length ? pool[Math.floor(Math.random() * pool.length)]!.id : null;
    return { coins, rarity, itemId };
  },
  async simulateError(): Promise<never> { await wait(500); throw new Error("err.server"); },
};

/** Attribute XP rises steadily; the tenth level is a deliberate review point. */
export function statLevelXp(level: number) { return 250 + (level - 1) * 100; }

/** Adds XP to the mission's life area without changing unrelated areas. */
export function applyStatXp(stats: LifeStat[], category: Category, amount: number): { stats: LifeStat[]; leveledUp: boolean } {
  let leveledUp = false;
  const next = stats.map((stat) => {
    if (stat.category !== category) return stat;
    let { level, xp } = stat;
    xp += Math.min(120, Math.max(0, amount));
    while (xp >= statLevelXp(level) && level < 10) { xp -= statLevelXp(level); level += 1; leveledUp = true; }
    if (level >= 10) xp = 0;
    return { ...stat, level, xp, nextLevelXp: statLevelXp(level) };
  });
  return { stats: next, leveledUp };
}

export function onTaskComplete(taskId: string) {
  return levelUpService.completeTask(taskId);
}
